# Generated by Django 5.1.3 on 2024-11-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
